---
driver:
  name: vagrant
  vm_hostname: 'netstat.local'

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: centos-5.11
- name: centos-6.6
- name: centos-7.1
- name: debian-6.0.10
  run_list: recipe[apt]
- name: debian-7.8
  run_list: recipe[apt]
- name: debian-8.1
  run_list: recipe[apt]
- name: fedora-19
  driver_config:
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-19_chef-provisionerless.box
- name: fedora-20
- name: fedora-21
- name: opensuse-13.2
  driver_config:
    box: opscode-opensuse-13.2
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_opensuse-13.2-x86_64_chef-provisionerless.box
- name: ubuntu-10.04
  run_list: recipe[apt]
- name: ubuntu-12.04
  run_list: recipe[apt]
- name: ubuntu-14.04
  run_list: recipe[apt]
- name: ubuntu-14.10
  run_list: recipe[apt]
- name: ubuntu-15.04
  run_list: recipe[apt]

suites:
- name: default
  run_list: recipe[netstat]
- name: chef13
  run_list: recipe[netstat]
  provisioner:
    product_name: chef
    channel: current
