rvm:
- 1.9.3
- 2.0.0
- 2.1
- 2.2

sudo: true

env:
  global:
  - KITCHEN_ARGS="--destroy=always"
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml
  matrix:
# CHEF_VERSION is only for unit tests, no for test-kitchen:
  - TESTS="style unit"  CHEF_VERSION="~> 11.0"
  - TESTS="style unit"  CHEF_VERSION="~> 12.0"
# Split up the test-kitchen run to avoid exceeding 50 minutes:
  - TESTS="integration" KITCHEN_REGEXP=centos
  - TESTS="integration" KITCHEN_REGEXP=debian
  - TESTS="integration" KITCHEN_REGEXP=ubuntu

matrix:
  exclude:
# Chef 12 requires Ruby 2:
  - rvm: 1.9.3
    env: TESTS="style unit"  CHEF_VERSION="~> 12.0"
# Chef 11 cannot resolve dependencies in Ruby 2.2 (mixlib-shellout):
  - rvm: 2.2
    env: TESTS="style unit"  CHEF_VERSION="~> 11.0"
# Disable integration tests in old Ruby versions:
  - rvm: 1.9.3
    env: TESTS="integration" KITCHEN_REGEXP=centos
  - rvm: 2.0.0
    env: TESTS="integration" KITCHEN_REGEXP=centos
  - rvm: 2.1
    env: TESTS="integration" KITCHEN_REGEXP=centos
  - rvm: 1.9.3
    env: TESTS="integration" KITCHEN_REGEXP=debian
  - rvm: 2.0.0
    env: TESTS="integration" KITCHEN_REGEXP=debian
  - rvm: 2.1
    env: TESTS="integration" KITCHEN_REGEXP=debian
  - rvm: 1.9.3
    env: TESTS="integration" KITCHEN_REGEXP=ubuntu
  - rvm: 2.0.0
    env: TESTS="integration" KITCHEN_REGEXP=ubuntu
  - rvm: 2.1
    env: TESTS="integration" KITCHEN_REGEXP=ubuntu

bundler_args: --without doc integration_vagrant integration_cloud guard

before_script:
- source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/0.3.0/scripts/start_docker.sh)

script:
- travis_retry bundle exec rake $TESTS

after_failure: cat docker_daemon.log
